/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Colores.Colores;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author BrunoDev
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    private Colores colores;

    public Ventana() {

        colores = new Colores();

        initComponents();
        initComponents2();
        initComponents3();
        initComponents4();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        menu1 = new javax.swing.JPanel();
        label = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        lbUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbUser1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbUser2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbUser3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        lbUser4 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        rSProgressCircle1 = new rojerusan.componentes.RSProgressCircle();
        jLabel36 = new javax.swing.JLabel();
        rSProgressCircle2 = new rojerusan.componentes.RSProgressCircle();
        rSProgressCircle3 = new rojerusan.componentes.RSProgressCircle();
        jLabel39 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        rSpTotalDeClientes = new rojerusan.componentes.RSProgressBar();
        rSpClientesPagos = new rojerusan.componentes.RSProgressBar();
        rSpClientesNoPadog = new rojerusan.componentes.RSProgressBar();
        rSpTotalDeClientes1 = new rojerusan.componentes.RSProgressBar();
        rSpClientesPagos1 = new rojerusan.componentes.RSProgressBar();
        rSpClientesNoPadog1 = new rojerusan.componentes.RSProgressBar();
        rSpClientesPagos2 = new rojerusan.componentes.RSProgressBar();
        rSpClientesNoPadog2 = new rojerusan.componentes.RSProgressBar();
        rSpTotalDeClientes2 = new rojerusan.componentes.RSProgressBar();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lbChek1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbChek2 = new javax.swing.JLabel();
        lbChek3 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbChek4 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lbChek5 = new javax.swing.JLabel();
        lbChek6 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbChek10 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lbChek8 = new javax.swing.JLabel();
        lbChek7 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        lbChek9 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(colores.getFondo1());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        menu1.setBackground(colores.getFondo3());
        menu1.setPreferredSize(new java.awt.Dimension(1050, 70));
        menu1.setLayout(new java.awt.BorderLayout());

        label.setBackground(new java.awt.Color(255, 0, 102));
        label.setOpaque(false);
        label.setPreferredSize(new java.awt.Dimension(500, 70));
        label.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(59, 198, 253));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 198, 253));
        jLabel1.setText("Dashboard");
        label.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, -1, -1));

        menu1.add(label, java.awt.BorderLayout.CENTER);

        user.setBackground(new java.awt.Color(0, 0, 0));
        user.setOpaque(false);
        user.setPreferredSize(new java.awt.Dimension(500, 70));
        user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/images.png"))); // NOI18N
        user.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 40, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("BrunoDev");
        user.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 100, 40));

        jLabel56.setBackground(colores.getFondo2());
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder-open-regular-36.png"))); // NOI18N
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel56MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel56MouseExited(evt);
            }
        });
        user.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 40, 35));

        jLabel57.setBackground(colores.getFondo2());
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bell-regular-36.png"))); // NOI18N
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel57MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel57MouseExited(evt);
            }
        });
        user.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 40, 35));

        menu1.add(user, java.awt.BorderLayout.LINE_END);

        jPanel1.add(menu1, java.awt.BorderLayout.PAGE_START);

        home.setBackground(new java.awt.Color(0, 0, 204));
        home.setPreferredSize(new java.awt.Dimension(980, 580));
        home.setRequestFocusEnabled(false);
        home.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jPanel3.setBackground(colores.getFondo2());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(colores.getFondo3());
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 580));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RD$ 905k");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 35));
        jPanel5.add(lbUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 35, 35));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Juana Guzman");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 20));
        jPanel5.add(lbUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 35, 35));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Maria Beltre");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 20));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RD$ 854k");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, 35));
        jPanel5.add(lbUser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 35, 35));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Zac Batista");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 120, 20));

        jLabel60.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("RD$ 798k");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 35));
        jPanel5.add(lbUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 35, 35));

        jLabel62.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 204, 204));
        jLabel62.setText("Pedro Pujols");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, 20));

        jLabel63.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("RD$ 754k");
        jPanel5.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, 35));

        jPanel3.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel7.setBackground(new java.awt.Color(102, 0, 102));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(780, 120));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBackground(colores.getFondo3());
        jPanel10.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(780, 120));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("RPD");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 30));

        rSProgressCircle1.setForeground(new java.awt.Color(251, 145, 134));
        rSProgressCircle1.setValue(98);
        rSProgressCircle1.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        jPanel10.add(rSProgressCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 60));

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("GFK");
        jPanel10.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, 30));

        rSProgressCircle2.setForeground(new java.awt.Color(226, 190, 144));
        rSProgressCircle2.setValue(68);
        rSProgressCircle2.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        jPanel10.add(rSProgressCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, 60));

        rSProgressCircle3.setForeground(new java.awt.Color(29, 121, 161));
        rSProgressCircle3.setValue(34);
        rSProgressCircle3.setFont(new java.awt.Font("Roboto Bold", 0, 12)); // NOI18N
        jPanel10.add(rSProgressCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 100, 60));

        jLabel39.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("AUY");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 100, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 780;
        gridBagConstraints.ipady = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel6.add(jPanel10, gridBagConstraints);

        jPanel7.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(new java.awt.Color(102, 102, 0));
        jPanel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(780, 460));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBackground(colores.getFondo3());
        jPanel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(490, 330));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("20%");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 40, 20));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("100%");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 20));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("60%");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 40, 20));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("80%");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, 20));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("40%");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 40, 20));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("0%");
        jLabel34.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 40, 20));

        jSeparator14.setBackground(colores.getFondo2());
        jPanel9.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 500, 10));

        rSpTotalDeClientes.setBackground(new java.awt.Color(73, 121, 226));
        rSpTotalDeClientes.setForeground(colores.getColorBar(9)
        );
        rSpTotalDeClientes.setMinimum(1);
        rSpTotalDeClientes.setOrientation(1);
        rSpTotalDeClientes.setToolTipText("");
        rSpTotalDeClientes.setValue(20);
        rSpTotalDeClientes.setBorderPainted(false);
        rSpTotalDeClientes.setOpaque(false);
        rSpTotalDeClientes.setString("");
        jPanel9.add(rSpTotalDeClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 22, 20, 230));

        rSpClientesPagos.setBackground(new java.awt.Color(73, 121, 226));
        rSpClientesPagos.setBorder(new javax.swing.border.MatteBorder(null));
        rSpClientesPagos.setForeground(colores.getColorBar(6));
        rSpClientesPagos.setMinimum(1);
        rSpClientesPagos.setOrientation(1);
        rSpClientesPagos.setToolTipText("");
        rSpClientesPagos.setValue(80);
        rSpClientesPagos.setBorderPainted(false);
        rSpClientesPagos.setOpaque(false);
        rSpClientesPagos.setString("");
        jPanel9.add(rSpClientesPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 22, 20, 230));

        rSpClientesNoPadog.setBackground(new java.awt.Color(73, 121, 226));
        rSpClientesNoPadog.setBorder(new javax.swing.border.MatteBorder(null));
        rSpClientesNoPadog.setForeground(colores.getColorBar(3));
        rSpClientesNoPadog.setMinimum(1);
        rSpClientesNoPadog.setOrientation(1);
        rSpClientesNoPadog.setToolTipText("");
        rSpClientesNoPadog.setValue(31);
        rSpClientesNoPadog.setBorderPainted(false);
        rSpClientesNoPadog.setOpaque(false);
        rSpClientesNoPadog.setString("");
        jPanel9.add(rSpClientesNoPadog, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 22, 20, 230));

        rSpTotalDeClientes1.setBackground(new java.awt.Color(73, 121, 226));
        rSpTotalDeClientes1.setBorder(new javax.swing.border.MatteBorder(null));
        rSpTotalDeClientes1.setForeground(colores.getColorBar(8));
        rSpTotalDeClientes1.setMinimum(1);
        rSpTotalDeClientes1.setOrientation(1);
        rSpTotalDeClientes1.setToolTipText("");
        rSpTotalDeClientes1.setValue(85);
        rSpTotalDeClientes1.setBorderPainted(false);
        rSpTotalDeClientes1.setOpaque(false);
        rSpTotalDeClientes1.setString("");
        jPanel9.add(rSpTotalDeClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 22, 20, 230));

        rSpClientesPagos1.setBackground(new java.awt.Color(73, 121, 226));
        rSpClientesPagos1.setBorder(new javax.swing.border.MatteBorder(null));
        rSpClientesPagos1.setForeground(colores.getColorBar(5));
        rSpClientesPagos1.setMinimum(1);
        rSpClientesPagos1.setOrientation(1);
        rSpClientesPagos1.setToolTipText("");
        rSpClientesPagos1.setValue(100);
        rSpClientesPagos1.setBorderPainted(false);
        rSpClientesPagos1.setOpaque(false);
        rSpClientesPagos1.setString("");
        jPanel9.add(rSpClientesPagos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 22, 20, 230));

        rSpClientesNoPadog1.setBackground(new java.awt.Color(73, 121, 226));
        rSpClientesNoPadog1.setBorder(new javax.swing.border.MatteBorder(null));
        rSpClientesNoPadog1.setForeground(colores.getColorBar(2));
        rSpClientesNoPadog1.setMinimum(1);
        rSpClientesNoPadog1.setOrientation(1);
        rSpClientesNoPadog1.setToolTipText("");
        rSpClientesNoPadog1.setValue(92);
        rSpClientesNoPadog1.setBorderPainted(false);
        rSpClientesNoPadog1.setOpaque(false);
        rSpClientesNoPadog1.setString("");
        jPanel9.add(rSpClientesNoPadog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 22, 20, 230));

        rSpClientesPagos2.setBackground(new java.awt.Color(73, 121, 226));
        rSpClientesPagos2.setBorder(new javax.swing.border.MatteBorder(null));
        rSpClientesPagos2.setForeground(colores.getColorBar(4));
        rSpClientesPagos2.setMinimum(1);
        rSpClientesPagos2.setOrientation(1);
        rSpClientesPagos2.setToolTipText("");
        rSpClientesPagos2.setValue(62);
        rSpClientesPagos2.setBorderPainted(false);
        rSpClientesPagos2.setOpaque(false);
        rSpClientesPagos2.setString("");
        jPanel9.add(rSpClientesPagos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 22, 20, 230));

        rSpClientesNoPadog2.setBackground(new java.awt.Color(73, 121, 226));
        rSpClientesNoPadog2.setBorder(new javax.swing.border.MatteBorder(null));
        rSpClientesNoPadog2.setForeground(colores.getColorBar(1));
        rSpClientesNoPadog2.setMinimum(1);
        rSpClientesNoPadog2.setOrientation(1);
        rSpClientesNoPadog2.setToolTipText("");
        rSpClientesNoPadog2.setValue(43);
        rSpClientesNoPadog2.setBorderPainted(false);
        rSpClientesNoPadog2.setOpaque(false);
        rSpClientesNoPadog2.setString("");
        jPanel9.add(rSpClientesNoPadog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 22, 20, 230));

        rSpTotalDeClientes2.setBackground(new java.awt.Color(73, 121, 226));
        rSpTotalDeClientes2.setBorder(new javax.swing.border.MatteBorder(null));
        rSpTotalDeClientes2.setForeground(colores.getColorBar(7));
        rSpTotalDeClientes2.setMinimum(1);
        rSpTotalDeClientes2.setOrientation(1);
        rSpTotalDeClientes2.setToolTipText("");
        rSpTotalDeClientes2.setValue(60);
        rSpTotalDeClientes2.setBorderPainted(false);
        rSpTotalDeClientes2.setOpaque(false);
        rSpTotalDeClientes2.setString("");
        jPanel9.add(rSpTotalDeClientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 22, 20, 230));

        jSeparator8.setBackground(colores.getFondo2());
        jPanel9.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 161, 500, 10));

        jSeparator13.setBackground(colores.getFondo2());
        jPanel9.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 69, 500, 10));

        jSeparator4.setBackground(colores.getFondo2());
        jPanel9.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 115, 500, 10));

        jSeparator5.setBackground(colores.getFondo2());
        jPanel9.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 207, 500, 10));

        jSeparator11.setBackground(colores.getFondo2());
        jPanel9.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 23, 500, 10));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 490;
        gridBagConstraints.ipady = 330;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel8.add(jPanel9, gridBagConstraints);

        jPanel12.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(780, 60));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 780;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel8.add(jPanel12, gridBagConstraints);

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(780, 70));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Enero del 2020");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 17, 230, 35));

        jButton1.setBackground(colores.getFondo3());
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(null);
        jPanel13.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 17, 120, 35));

        jButton2.setBackground(new java.awt.Color(81, 137, 255));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Next");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 17, 120, 35));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel8.add(jPanel13, gridBagConstraints);

        jPanel11.setBackground(colores.getFondo3());
        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(270, 330));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbChek1.setBackground(new java.awt.Color(0, 204, 102));
        lbChek1.setOpaque(true);
        jPanel11.add(lbChek1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("Coca – Cola");
        jPanel11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 210, -1));

        jLabel38.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("Lay’s");
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, -1));

        lbChek2.setBackground(new java.awt.Color(0, 204, 102));
        lbChek2.setOpaque(true);
        jPanel11.add(lbChek2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 15, 15));

        lbChek3.setBackground(new java.awt.Color(0, 204, 102));
        lbChek3.setOpaque(true);
        jPanel11.add(lbChek3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 15, 15));

        jLabel41.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Playstation");
        jPanel11.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 210, -1));

        lbChek4.setBackground(new java.awt.Color(0, 204, 102));
        lbChek4.setOpaque(true);
        jPanel11.add(lbChek4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 15, 15));

        jLabel43.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("Toyota Corolla");
        jPanel11.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, -1));

        jLabel44.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("Iphone");
        jPanel11.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        lbChek5.setBackground(new java.awt.Color(0, 204, 102));
        lbChek5.setOpaque(true);
        jPanel11.add(lbChek5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 15, 15));

        lbChek6.setBackground(new java.awt.Color(0, 204, 102));
        lbChek6.setOpaque(true);
        jPanel11.add(lbChek6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 15, 15));

        jLabel47.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("Angry Birds");
        jPanel11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        jLabel48.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("Ipad");
        jPanel11.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, -1));

        lbChek10.setBackground(new java.awt.Color(0, 204, 102));
        lbChek10.setOpaque(true);
        jPanel11.add(lbChek10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 15, 15));

        jLabel50.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 204, 204));
        jLabel50.setText("Cubo Rubik");
        jPanel11.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, -1));

        lbChek8.setBackground(new java.awt.Color(0, 204, 102));
        lbChek8.setOpaque(true);
        jPanel11.add(lbChek8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 15, 15));

        lbChek7.setBackground(new java.awt.Color(0, 204, 102));
        lbChek7.setOpaque(true);
        jPanel11.add(lbChek7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 15, 15));

        jLabel53.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(204, 204, 204));
        jLabel53.setText("Harry Potter");
        jPanel11.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, -1));

        lbChek9.setBackground(new java.awt.Color(0, 204, 102));
        lbChek9.setOpaque(true);
        jPanel11.add(lbChek9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 15, 15));

        jLabel55.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(204, 204, 204));
        jLabel55.setText("Star Wars");
        jPanel11.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel8.add(jPanel11, gridBagConstraints);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel3);

        home.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(home, java.awt.BorderLayout.CENTER);

        menu2.setBackground(colores.getFondo2());
        menu2.setMinimumSize(new java.awt.Dimension(0, 0));
        menu2.setPreferredSize(new java.awt.Dimension(70, 580));
        menu2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(70, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 102, 51));
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 4, 35));

        jLabel7.setBackground(colores.getFondo2());
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home-regular-36.png"))); // NOI18N
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 35));

        jLabel28.setBackground(colores.getFondo2());
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help-circle-regular-36.png"))); // NOI18N
        jLabel28.setOpaque(true);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
        });
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 70, 35));

        jLabel29.setBackground(colores.getFondo3());
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bar-chart-regular-36.png"))); // NOI18N
        jLabel29.setOpaque(true);
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel29MouseExited(evt);
            }
        });
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 70, 35));

        jLabel30.setBackground(colores.getFondo2());
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/revision-regular-36.png"))); // NOI18N
        jLabel30.setOpaque(true);
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 70, 35));

        menu2.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(153, 0, 51));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(70, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(colores.getFondo2());
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/door-open-regular-36.png"))); // NOI18N
        jLabel31.setOpaque(true);
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 70, 35));

        menu2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel1.add(menu2, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setBackground(colores.getFondo3());
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel7.setBackground(colores.getFondo2());
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseEntered

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseEntered

    private void jLabel29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseExited

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseExited

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel56MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel56MouseEntered

    private void jLabel56MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel56MouseExited

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jLabel57MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel57MouseEntered

    private void jLabel57MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel57MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void initComponents2() {
        this.setLocationRelativeTo(null);
        this.setTitle("BrunoDev - Dashboard Java Swing");
        this.setSize(1100, 650);
    }

    private void initComponents3() {
        ImageIcon ima = new ImageIcon(getClass().getResource("/Icons/images.png"));
        Icon ico = new ImageIcon(ima.getImage().getScaledInstance(lbUser.getWidth(), lbUser.getHeight(), Image.SCALE_DEFAULT));
        lbUser.setIcon(ico);

        ImageIcon ima1 = new ImageIcon(getClass().getResource("/Icons/images1.png"));
        Icon ico1 = new ImageIcon(ima1.getImage().getScaledInstance(lbUser1.getWidth(), lbUser1.getHeight(), Image.SCALE_DEFAULT));
        lbUser1.setIcon(ico1);

        ImageIcon ima2 = new ImageIcon(getClass().getResource("/Icons/images4.png"));
        Icon ico2 = new ImageIcon(ima2.getImage().getScaledInstance(lbUser2.getWidth(), lbUser2.getHeight(), Image.SCALE_DEFAULT));
        lbUser2.setIcon(ico2);

        ImageIcon ima3 = new ImageIcon(getClass().getResource("/Icons/images3.png"));
        Icon ico3 = new ImageIcon(ima3.getImage().getScaledInstance(lbUser3.getWidth(), lbUser3.getHeight(), Image.SCALE_DEFAULT));
        lbUser3.setIcon(ico3);

        ImageIcon ima4 = new ImageIcon(getClass().getResource("/Icons/images2.png"));
        Icon ico4 = new ImageIcon(ima4.getImage().getScaledInstance(lbUser4.getWidth(), lbUser4.getHeight(), Image.SCALE_DEFAULT));
        lbUser4.setIcon(ico4);
    }
    
    private void initComponents4() {
        lbChek1.setBackground(colores.getColorCheck(0));
        lbChek2.setBackground(colores.getColorCheck(1));
        lbChek3.setBackground(colores.getColorCheck(2));
        lbChek4.setBackground(colores.getColorCheck(3));
        lbChek5.setBackground(colores.getColorCheck(4));
        lbChek6.setBackground(colores.getColorCheck(5));
        lbChek7.setBackground(colores.getColorCheck(6));
        lbChek8.setBackground(colores.getColorCheck(7));
        lbChek9.setBackground(colores.getColorCheck(8));
        lbChek10.setBackground(colores.getColorCheck(9));
        
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel label;
    private javax.swing.JLabel lbChek1;
    private javax.swing.JLabel lbChek10;
    private javax.swing.JLabel lbChek2;
    private javax.swing.JLabel lbChek3;
    private javax.swing.JLabel lbChek4;
    private javax.swing.JLabel lbChek5;
    private javax.swing.JLabel lbChek6;
    private javax.swing.JLabel lbChek7;
    private javax.swing.JLabel lbChek8;
    private javax.swing.JLabel lbChek9;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUser1;
    private javax.swing.JLabel lbUser2;
    private javax.swing.JLabel lbUser3;
    private javax.swing.JLabel lbUser4;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private rojerusan.componentes.RSProgressCircle rSProgressCircle1;
    private rojerusan.componentes.RSProgressCircle rSProgressCircle2;
    private rojerusan.componentes.RSProgressCircle rSProgressCircle3;
    private rojerusan.componentes.RSProgressBar rSpClientesNoPadog;
    private rojerusan.componentes.RSProgressBar rSpClientesNoPadog1;
    private rojerusan.componentes.RSProgressBar rSpClientesNoPadog2;
    private rojerusan.componentes.RSProgressBar rSpClientesPagos;
    private rojerusan.componentes.RSProgressBar rSpClientesPagos1;
    private rojerusan.componentes.RSProgressBar rSpClientesPagos2;
    private rojerusan.componentes.RSProgressBar rSpTotalDeClientes;
    private rojerusan.componentes.RSProgressBar rSpTotalDeClientes1;
    private rojerusan.componentes.RSProgressBar rSpTotalDeClientes2;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
